### ISSUE TITLE
Gzweb Dockerfile fails to build

### ISSUE THREAD

**Issue by stphnsmpsn** [osrf/docker_images#334]
I am unable to create a container for gzweb using the provided Dockerfile. The following errors occur: 

```
Scanning dependencies of target gzcoarse
[ 50%] Building CXX object tools/CMakeFiles/gzcoarse.dir/gzcoarse.cc.o
[100%] Linking CXX executable gzcoarse
[100%] Built target gzcoarse
/root/gzweb/node_modules/env-paths/index.js:7
const {env} = process;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/gzweb/node_modules/node-gyp/bin/node-gyp.js:7:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
/root/gzweb/node_modules/env-paths/index.js:7
const {env} = process;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/gzweb/node_modules/node-gyp/bin/node-gyp.js:7:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
There are node-gyp build errors, exiting.
The command '/bin/sh -c hg up default     && xvfb-run -s "-screen 0 1280x1024x24" ./deploy.sh -m -t' returned a non-zero code: 1
```

**Comment by ruffsl** [comment]
Related?: https://github.com/osrf/docker_images/issues/333#issuecomment-546610760

**Comment by stphnsmpsn** [comment]
@ruffsl, updating node and forcing node-gyp to use version 3.8.0 in package.json fixed my problem:

```
RUN sed -i 's/"node-gyp": "",/"node-gyp": "3.8.0",/g' package.json
```

```
RUN apt-get update
RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash
RUN apt-get install -y nodejs
```
