### ISSUE TITLE
python-tk is dropped from kinetic and melodic images

### ISSUE THREAD

**Issue by pazeshun** [osrf/docker_images#423]
I'm not sure this is a bug, but `python-tk` package is dropped from `osrf/ros:<kinetic/melodic>-desktop-<xenial/bionic>`:
```
$ sudo docker pull osrf/ros:kinetic-desktop-xenial
$ sudo docker run -it osrf/ros:kinetic-desktop-xenial /bin/bash
# dpkg -l python-tk
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
un  python-tk                   <none>             <none>             (no description available)
```
```
$ sudo docker pull osrf/ros:melodic-desktop-bionic
$ sudo docker run -it osrf/ros:melodic-desktop-bionic /bin/bash
# dpkg -l python-tk
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
un  python-tk                   <none>             <none>             (no description available)
```
Without `python-tk`, we cannot execute `import matplotlib.pyplot`:
```
# python
Python 2.7.12 (default, Apr 15 2020, 17:07:12) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
```

I think `python-tk` was installed on kinetic and melodic images about a month ago.
I don't know how to currently get these old images for confirmation, so I instead confirmed `python-tk` is installed on `osrf/ros:indigo-desktop-trusty`:
```
$ sudo docker pull osrf/ros:indigo-desktop-trusty
$ sudo docker run -it osrf/ros:indigo-desktop-trusty /bin/bash
# dpkg -l python-tk
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  python-tk                   2.7.5-1ubuntu1     amd64              Tkinter - Writing Tk applications with Python
```
`python-tk` is depended on by `python-opengl`, `python-matplotlib`, and `python`.
But their dependencies are `Suggests` or `Recommends`, which means `python-tk` might be explicitly installed:
```
# apt-cache rdepends python-tk
python-tk
Reverse Depends:
  python-opengl
  python-matplotlib
  python
# apt-cache depends python
python
  Depends: python2.7
  Depends: python-minimal
  Depends: libpython-stdlib
  Suggests: <python-doc>
  Suggests: python-tk
  Conflicts: <python-central>
  Breaks: <python-bz2>
  Breaks: <python-csv>
  Breaks: <python-email>
  Breaks: <update-manager-core>
  Replaces: python-dev
# apt-cache depends python-opengl
python-opengl
  Depends: <python:any>
    python
  Depends: <python:any>
    python
  Depends: <python-ctypes>
    python
 |Depends: libgl1-mesa-glx
  Depends: <libgl1>
    libgl1-mesa-glx
 |Depends: libglu1-mesa
  Depends: <libglu1>
    libglu1-mesa
  Depends: freeglut3
  Suggests: python-tk
  Suggests: python-numpy
  Suggests: <libgle3>
# apt-cache depends python-matplotlib
python-matplotlib
  Depends: python-dateutil
  Depends: python-matplotlib-data
  Depends: python-pyparsing
  Depends: python-tz
  Depends: python
  Depends: python
  Depends: python-numpy
  Depends: <python-numpy-abi9>
    python-numpy
  Depends: python-support
  Depends: libc6
  Depends: libfreetype6
  Depends: libgcc1
  Depends: libgdk-pixbuf2.0-0
  Depends: libglib2.0-0
  Depends: libgtk2.0-0
  Depends: libpng12-0
  Depends: libstdc++6
  Depends: libtcl8.6
  Depends: libtk8.6
  Suggests: <dvipng>
  Suggests: <gir1.2-gtk-3.0>
  Suggests: <ghostscript>
  Suggests: <inkscape>
  Suggests: <ipython>
  Suggests: <librsvg2-common>
  Suggests: python-cairo
  Suggests: python-configobj
  Suggests: <python-excelerator>
  Suggests: <python-gobject>
  Suggests: python-gtk2
  Suggests: <python-matplotlib-doc>
  Suggests: python-nose
  Suggests: python-qt4
  Suggests: <python-scipy>
  Suggests: python-sip
  Suggests: <python-tornado>
  Suggests: <python-traits>
  Suggests: python-wxgtk2.8
  Suggests: <texlive-extra-utils>
  Suggests: <texlive-latex-extra>
  Suggests: <ttf-staypuft>
  Recommends: python-glade2
  Recommends: python-imaging
  Recommends: python-tk
  Enhances: <ipython>
```

**Comment by mikaelarguedas** [comment]
You're correct, up until ~1month ago the "Recommends" dependencies were installed. In order to reduce the size of the images and limit the number of unused packages, these images now only provide the required dependencies (`Depends`).

Relevant links:
- Announcement on ROS Discourse: https://discourse.ros.org/t/announcement-trimmed-ros-gazebo-docker-images-released/14342
- PRs: [templates](https://github.com/osrf/docker_templates/pull/82), [update to the dockerfiles](https://github.com/osrf/docker_images/pull/357)

**Comment by pazeshun** [comment]
@mikaelarguedas Thank you for your rapid and valuable response!
Now I understand dropping `python-tk` is not a bug and I have to install it explicitly.
Thanks again.
