### ISSUE TITLE
Automatic PR generation fails to push

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#530]
Last night the foxy and rolling images were out of date and CI tried to creat PRs to update them but failed with:

```
    HUB_REPO: ros
    HUB_RELEASE: rolling
    HUB_OS_NAME: ubuntu
    HUB_OS_CODE_NAME: focal
Traceback (most recent call last):
HUB_REPO:  ros
  File "/home/runner/work/docker_images/docker_images/.ci/ci_script.py", line 158, in main
HUB_RELEASE:  rolling
    test_diffs(diffs)
HUB_OS_NAME:  ubuntu
  File "/home/runner/work/docker_images/docker_images/.ci/ci_script.py", line 51, in test_diffs
HUB_OS_CODE_NAME:  focal
Error:     raise ValueError('Autogenerated files are not up to date')
GIT_UPSTREAM_REPO_SLUG:  osrf/docker_images
ValueError: Autogenerated files are not up to date

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/docker_images/docker_images/.ci/ci_script.py", line 224, in main
    repo.git.push(
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/git/cmd.py", line 1011, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/git/cmd.py", line 828, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push --force upstream_pr ros/rolling/ubuntu/focal:ros/rolling/ubuntu/focalNone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/docker_images/docker_images/.ci/ci_script.py", line 279, in <module>
    main()
  File "/home/runner/work/docker_images/docker_images/.ci/ci_script.py", line 228, in main
    raise ValueError(
ValueError: Force push to branch:ros/rolling/ubuntu/focal failed! Stderr omitted to protect secrets.
---
```

@ruffsl FYI

**Comment by ruffsl** [comment]
Why is `None` appended to the end of the git push command?

```
  cmdline: git push --force upstream_pr ros/rolling/ubuntu/focal:ros/rolling/ubuntu/focalNone
```

**Comment by mikaelarguedas** [comment]
I suspect this is a misleading print as we use the [exact same string before and after the `:`](https://github.com/osrf/docker_images/blob/e95025e4b17349438a4b68951bd6d8702b0020be/.ci/ci_script.py#L225) Maybe something changed in the permissions / token of the `osrf-docker-builder` user? I do not have access to that account so am unable to look further into it.
Maybe @tfoote or @nuclearsandwich would know more ?
The last successful push was on April 28th
The first failed push was on May 5th

**Comment by tfoote** [comment]
My best guess is that the keys used to push might have been invalidated? Possibly relating to codecov security @nuclearsandwich I see an attached specific key instead of leveraging single use github generated keys which I think can work for our use case: https://docs.github.com/en/actions/reference/authentication-in-a-workflow

**Comment by mikaelarguedas** [comment]
@tfoote @nuclearsandwich Any news on this topic ? I would love to stop opening these PRs by hand ^^'
